export const PARAM_UPDATED = 'PARAM_UPDATED';
export const PROFILE_SELECTED = 'PROFILE_SELECTED';
export const PROFILE_ADDED = 'PROFILE_ADDED';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_REMOVED = 'PROFILE_REMOVED';
export const ALL_PROFILES_REMOVED = 'ALL_PROFILES_REMOVED';